name: Gradle Build
on:
  workflow_dispatch:

jobs:
  build:
    name: Build WorldEdit
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6

    - name: Set up JDK
      uses: actions/setup-java@v5
      with:
        java-version: 25
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v5

    - name: Execute Gradle build
      run: ./gradlew build -s

    - uses: actions/upload-artifact@v6
      name: Upload JARs
      with:
        name: worldedit-jars
        path: '**/build/libs/*.jar'
